# Generated by Django 6.0.6 on 2026-08-18 07:40

import core.models
import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('category', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('default_title', models.CharField(max_length=255)),
                ('default_content', models.TextField(blank=True)),
                ('receivers', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('viewers', models.JSONField(blank=True, default=list)),
                ('public_receivers', models.JSONField(blank=True, default=list)),
                ('cooperation_department', models.CharField(blank=True, max_length=100)),
                ('agreement', models.CharField(blank=True, max_length=255)),
                ('document_layout', models.CharField(default='basic', max_length=30)),
                ('line_item_rows', models.PositiveSmallIntegerField(default=8)),
                ('is_enabled', models.BooleanField(default=True)),
                ('recent_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('portal_name', models.CharField(default='더 위 시스템', max_length=100)),
                ('annual_leave_by_year', models.JSONField(default=core.models.default_annual_leave_policy)),
                ('monthly_leave_per_month', models.PositiveSmallIntegerField(default=1)),
                ('admin_otp_enabled', models.BooleanField(default=True)),
                ('settings_password_enabled', models.BooleanField(default=True)),
                ('admin_document_access_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('position', models.CharField(blank=True, max_length=50)),
                ('hire_date', models.DateField(default=datetime.date.today)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.department')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('prefix', models.CharField(db_index=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('department_name', models.CharField(max_length=100)),
                ('form_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('작성중', '작성중'), ('결재대기', '결재대기'), ('검토중', '검토중'), ('진행중', '진행중'), ('완료', '완료'), ('반려', '반려'), ('취소', '취소')], default='작성중', max_length=20)),
                ('drafted_at', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('document_no', models.CharField(blank=True, max_length=60)),
                ('effective_date', models.DateField(default=datetime.date.today)),
                ('cooperation_department', models.CharField(blank=True, max_length=100)),
                ('agreement', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('urgent', models.BooleanField(default=False)),
                ('received_request', models.BooleanField(default=False)),
                ('can_cancel', models.BooleanField(default=False)),
                ('can_reuse', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=True)),
                ('department_visible', models.BooleanField(default=True)),
                ('receivers', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('viewers', models.JSONField(blank=True, default=list)),
                ('public_receivers', models.JSONField(blank=True, default=list)),
                ('linked_documents', models.JSONField(blank=True, default=list)),
                ('document_layout', models.CharField(default='basic', max_length=30)),
                ('form_fields', models.JSONField(blank=True, default=dict)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drafter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafted_documents', to=settings.AUTH_USER_MODEL)),
                ('form_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.approvalformtemplate')),
            ],
            options={
                'ordering': ['-drafted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=120)),
                ('base64_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.approvaldocument')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=60, unique=True)),
                ('category', models.CharField(max_length=80)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_label', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=500)),
                ('snapshot', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='core.approvaldocument')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=40, unique=True)),
                ('leave_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('승인대기', '승인대기'), ('승인', '승인'), ('반려', '반려'), ('취소', '취소')], default='승인대기', max_length=20)),
                ('ceo_status', models.CharField(default='진행중', max_length=20)),
                ('rejected_by', models.CharField(blank=True, max_length=100)),
                ('direct_entry', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('step_type', models.CharField(default='결재', max_length=30)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='예정', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('delegated_by', models.CharField(blank=True, max_length=100)),
                ('requires_original_approval', models.BooleanField(default=False)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.approvaldocument')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('document', 'order'), name='unique_document_step_order')],
            },
        ),
    ]
