# Generated by Django 6.0.6 on 2026-08-20 01:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsetting',
            name='custom_logo_base64',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portalsetting',
            name='custom_logo_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='portalsetting',
            name='document_category_viewer_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='portalsetting',
            name='enabled_app_ids',
            field=models.JSONField(default=core.models.default_enabled_apps),
        ),
        migrations.AddField(
            model_name='portalsetting',
            name='organization_wide_document_categories',
            field=models.JSONField(default=core.models.default_wide_document_categories),
        ),
    ]
